sudo: required

dist: trusty

language: scala

# This does not work because these packages are disallowed
#addons:
#  apt:
#    packages:
#    - lxc
#    - lxctl

cache:
  apt: true
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_install:
- sudo apt-cache search lxc
- sudo apt-get install lxc
- sudo apt-get install lxctl
- dpkg-query -s lxc
- dpkg-query -s lxctl

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm