version: '2'

services:
  kdc-kadmin:
    build: ./kdc-kadmin
    env_file: kerberos.env
    #ports:
    #  - "749:749"
    #  - "750:750"
    #volumes:
    #  - /dev/urandom:/dev/random

  #kerberos-client:
    #build: ./kerberos-client
    #env_file: kerberos.env
    #links:
    #  - kdc-kadmin
    #volumes:
    #  - ../:/tmp/kadmin/