version: "2"
services:
  kdc-kadmin:
    build: ./kdc-kadmin
    hostname: kdc-kadmin
    domainname: example.com
    # env_file: kerberos.env
    ports:
      - "749:749"
      - "750:750"
    volumes:
      # This is essential because otherwise the container will take an enormous amount
      # of time to obtain enough entropy. If it is even able to do so.
      - /dev/urandom:/dev/random

  #docker build --tag="kdc-kadmin" ./kdc-kadmin
  #docker run \
  #  --name="kdc-kadmin" \
  #  --hostname="kdc-kadmin.example.com" \ # --env-file="kerberos.env" # --env REALM=YOURDOMAIN.COM
  #  --volume="/dev/urandom:/dev/random" \
  #  --expose="749:749" \
  #  --expose="750:750" \
  #  --detach \
  #  kdc-kadmin

  kerberos-client:
    build: ./kerberos-client
    env_file: kerberos.env
    links:
      - kdc-kadmin
    volumes:
      - ../:/tmp/kadmin/

  #docker build --tag="kerberos-client" ./kerberos-client
  #docker run \
  #  --name="kerberos-client" \
  #  --env-file="kerberos.env" \ # --env REALM=YOURDOMAIN.COM
  #  --volume="..:/tmp/kadmin" \
  #  kerberos-client
